### ISSUE TITLE
GitHub Pages didn't update

### ISSUE THREAD

**Issue by ituitis-otal18** [itu-itis-2019/assignment1-ituitis-otal18#1]
I managed to commit my updated files to the GitHub repository but my updates didn't show up at the gh-pages link. I searched for a solution however I couldn't solve this problem.

**Comment by damienjadeduff** [comment]
First, try doing a full refresh on your page from your browser. Failing that, try looking at the page from a different device or even network, in case something is caching it. You should also write in your issue what you have tried.

**Comment by ituitis-otal18** [comment]
I cleared my browser's cache and tried again. After that, I tried from another network, device and even from another OS but the problem still exists.

**Comment by damienjadeduff** [comment]
It's hard for me to know what was supposed to be seen - if you haven't already solved it I would need more specifics. Check the branch you are pushing on, check error messages to ensure it does push, don't forget to pull before push, etc.
